### ISSUE TITLE
1.19 experimental builds?

### ISSUE THREAD

**Issue by yavko** [Pearl-Project/Pearl#11]
Hello, purpur, and pufferfish have 1.19 experimental versions, could you guys please also provide builds? Thx for the work on pearl!

**Comment by minhh2792** [comment]
Paper just released 1.19 stable build, I will wait for Pufferfish to upstream and merge their dev/1.19

**Comment by yavko** [comment]
> Paper just released 1.19 stable build, I will wait for Pufferfish to upstream and merge their dev/1.19

I believe they have!
